;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((emacs-lisp-mode . ((fill-column . 80)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . t)
                     (elisp-lint-indent-specs . ((org-mcp--modify-and-save . 3)
                                                 (org-mcp--with-visiting-org-file . 2)
                                                 (org-mcp--with-uri-prefix-dispatch . 1)
                                                 (org-mcp--with-org-file . 1)
                                                 (org-mcp-test--assert-error-and-file . 1)
                                                 (org-mcp-test--assert-archive-error . 1)
                                                 (org-mcp-test--assert-refile-error . 1)
                                                 (org-mcp-test--with-enabled . defun)
                                                 (org-mcp-test--with-temp-org-files . 1)
                                                 (org-mcp-test--with-outline-metadata-nodes . 0)
                                                 (org-mcp-test--with-file-buffer . 2)
                                                 (org-mcp-test--with-get-todo-config-result . 1)
                                                 (org-mcp-test--with-get-agenda-config-result . 1)
                                                 (org-mcp-test--with-custom-agenda-result . 2)
                                                 (org-mcp-test--call-read-headline-expecting-error . 0)
                                                 (org-mcp-test--with-add-todo-setup . 2)
                                                 (org-mcp-test--with-id-tracking . 2)
                                                 (org-mcp-test--with-id-setup . 2)
                                                 (org-mcp-test--with-archive-setup . 3)
                                                 (org-mcp-test--with-archive-file . 2)
                                                 (org-mcp-test--get-tag-config-and-check . defun)
                                                 (org-mcp-test--with-set-planning . 2)
                                                 (org-mcp-test--assert-set-planning-error . 2)
                                                 (org-mcp-test--with-refile-files . 3)
                                                 (org-mcp-test--with-cross-refile-no-id-leak . 1)
                                                 (org-mcp-test--assert-refile-no-id-leak . 1)
                                                 (org-mcp-test--assert-same-file-refile-error . 2)
                                                 (org-mcp-test--assert-refile-noop . 2)
                                                 (org-mcp-test--with-archive-simple . 0)
                                                 (org-mcp-test--with-source-write-stub . 1)
                                                 (org-mcp-test--should-archive-moved . 1)
                                                 (org-mcp-test--should-archive-aborted . 0)
                                                 (org-mcp-test--assert-archive-task-unsaved . 0)
                                                 (org-mcp-test--assert-archive-unsaved-dest . 1)
                                                 (org-mcp-test--assert-archive-to-custom . 1)
                                                 (org-mcp-test--with-agenda-and-foreign-file . 0)
                                                 (org-mcp-test--assert-edit-body-with-id . 1)
                                                 (org-mcp-test--assert-edit-body-error . 1)
                                                 (org-mcp-test--assert-edit-body-repeated-error . 1)
                                                 (org-mcp-test--assert-edit-body-empty-timestamp . 1)
                                                 (org-mcp-test--asserting-no-modified-buffer-killed . 0)
                                                 (org-mcp-test--asserting-edit-body-kills-no-modified-buffer . 0)
                                                 (org-mcp-test--with-id-fallback-scan . 1)
                                                 (org-mcp-test--assert-clear-done-closed . 1)
                                                 (org-mcp-test--assert-update-todo-error . 1)
                                                 (org-mcp-test--add-new-task-and-check . 3)
                                                 (org-mcp-test--add-child-task-and-check . 2)
                                                 (org-mcp-test--add-review-after-sibling . 1)
                                                 (org-mcp-test--assert-add-child-position-error . 3)
                                                 (org-mcp-test--assert-add-todo-wire-null-accepted . 1)
                                                 (mcp-server-lib-ert-with-server . defun))))))
