name: melpazoid
on: [push, pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install emacs && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: |
            (org-mcp :fetcher github :repo "laurynas-biveinis/org-mcp")
        run: echo "$GITHUB_REF" && make -C ~/melpazoid